### PR TITLE
Fix launcher

### LINKED ISSUE #455: Failed to start gauge API: Timed out connecting to java (1.1.1)
### Describe the bug
Getting loads of these error when running on the latest version of gauge and gauge-java

### What command(s) did you run when you found the bug?

For e.g. 
```
mvn clean test
```

### Output, stack trace or logs related to the bug 

```sh
Failed to start gauge API: Timed out connecting to java
```

#### Gauge (Output of `gauge -v`)

```sh
Gauge version: 1.1.1
Plugins
-------
html-report (4.0.11)
java (0.7.8)
reportportal (1.6.0)
reportserver (0.2.0)
screenshot (0.0.1)
xml-report (0.2.3)
```

#### Operating System information
OSx

### PR DESCRIPTION
**Pull request by BugDiver**
Fixes #455 , #454

### CODE REVIEW

File: src/main/java/com/thoughtworks/gauge/command/StartCommand.java [hunk 1]
```diff
@@ -23,17 +23,20 @@ public void execute() throws Exception {
...
         staticScanner.addStepsToRegistry();
         Server server;
-        boolean multithreading = false;
-        int stream = 1;
-        String streamValue = System.getenv(STREAMS_COUNT_ENV);
-        if (streamValue != null && !streamValue.isEmpty()) {
-            stream = Integer.parseInt(streamValue);
-            multithreading = true;
-            Logger.debug("assuming enable_multithreading=true, because " + STREAMS_COUNT_ENV + " is set to " + streamValue);
+        boolean multithreading = System.getenv(ENABLE_MULTITHREADING_ENV).toLowerCase() == "true";
```
Comment (zabil) [inline src/main/java/com/thoughtworks/gauge/command/StartCommand.java:27]: Please use https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Boolean.html#valueOf(java.lang.String)

Comment (sriv) [reply src/main/java/com/thoughtworks/gauge/command/StartCommand.java]: fixed in later commit
