### PR TITLE
Consider src/main/java and src/test/java as a default implementaion location

### LINKED ISSUE #375: Gauge specs execution should work properly when implementation files are inside src/main/java
### Expected behavior
specs execution should work properly

### Actual behavior
Step implementation not found

### Steps to reproduce
1. create a sample Gauge Java project
2. move step implementaion from `src/test/java` to `src/main/java`
3. `gauge run`

### Gauge version
```
Gauge version: 1.0.7

Plugins
-------
html-report (4.0.9)
java (0.7.4)
```

**Note:** works fine with gauge java 0.7.3. Refer to [this issue](https://github.com/getgauge/gauge/issues/1579) for more details.

### PR DESCRIPTION
**Pull request by negiDharmendra**
Fixes #375

### CODE REVIEW

File: src/main/java/com/thoughtworks/gauge/FileHelper.java [hunk 1]
```diff
@@ -82,4 +83,14 @@ public static File getDefaultImplFileName(String suffix, int count) {
     private static String getDefaultStepImplDir() {
         return getAbsolutePath(DEFAULT_SRC_DIR).toString();
     }
+    private static List<String> getDefaultStepImplDirs() {
+        List<String> dirs = new ArrayList<>();
+        for (String dir : DEFAULT_SRC_DIRS.split(",")) {
```
Comment (zabil) [inline src/main/java/com/thoughtworks/gauge/FileHelper.java]:
```suggestion
        for (String dir : DEFAULT_SRC_DIRS) {
```

After declaring DEFAULT_SRC_DIRS as an array

File: src/main/java/com/thoughtworks/gauge/GaugeConstant.java [hunk 2]
```diff
@@ -21,6 +21,7 @@
     public static final String GAUGE_PROJECT_ROOT = "GAUGE_PROJECT_ROOT";
     public static final String GAUGE_CUSTOM_COMPILE_DIR = "gauge_custom_compile_dir";
     public static final String DEFAULT_SRC_DIR = "src/test/java";
+    public static final String DEFAULT_SRC_DIRS = String.format("src/main/java,%s", DEFAULT_SRC_DIR);
```
Comment (zabil) [inline src/main/java/com/thoughtworks/gauge/GaugeConstant.java]: Please initialize this as a static array instead of using a string format 
```suggestion
    public static final String[] DEFAULT_SRC_DIRS = { "src/main/java", DEFAULT_SRC_DIR };
```

**Comment by zabil** [comment]
Can we also have a test for this in `FileHelperTest.java`
